name: findata
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - cattrs==25.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - curl-cffi==0.13.0
      - frozendict==2.4.7
      - h11==0.16.0
      - idna==3.11
      - multitasking==0.0.12
      - numpy==2.3.5
      - outcome==1.3.0.post0
      - packaging==25.0
      - pandas==2.3.3
      - peewee==3.18.3
      - platformdirs==4.5.1
      - protobuf==6.33.2
      - pycparser==2.23
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - requests==2.32.5
      - requests-cache==1.2.1
      - selenium==4.39.0
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - trio==0.32.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - url-normalize==2.2.1
      - urllib3==2.6.1
      - webdriver-manager==4.0.2
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wsproto==1.3.2
      - yfinance==0.2.66
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/findata
